### PR TITLE
Release 21.9.0

### PR DESCRIPTION
**Pull request by adiroiban**
This is the release branch for 21.9.0

### CODE REVIEW

**Comment by adiroiban** [comment]
Please check that the release candidate is ok https://pypi.org/project/towncrier/21.9.0rc1/

If you have tested , please report the test results here.

Thanks!

**Comment by decaz** [comment]
@adiroiban RC was tested for a long time and it 21.9.0 can be released now.

**Comment by adiroiban** [comment]
Thanks for the confirmation.
I have pushed the final release.

**Comment by adiroiban** [comment]
doing that. If all is ok, please review and approve this PR :p

**Comment by decaz** [comment]
@adiroiban there is still version 21.3.0 on PyPI. Are you trying to release 21.9.0 or 22.2.0?

**Comment by adiroiban** [comment]
Finally https://pypi.org/project/towncrier/21.9.0/ :)

**Comment by adiroiban** [comment]
I have relaxed the PR merge rules to allow a merge even without an approved review.

This PR was waiting since September to be reviewed and nobody step in.

So I will consider that the project is now in "emergency mode" and we will try to move it forward as best as we can :(

**Pull request merged**
