### PR TITLE
Update the documentation for the release process.

### PR DESCRIPTION
**Pull request by adiroiban**
# Description

Update the releaes process docs.

### CODE REVIEW

**Comment by adiroiban** [comment]
@webknjaz Let me know if the instruction make sense.
I added a note about creating the discussion.

----------

> As for signing, I can look into it sometime, if there's any interest.

I think that signing would be great.

I didn't had time to check how this is done. 

Right now, the PyPi packages are generated by GitHub Actions ... so no signing is involved.

If you want to see towncrier packages signed, feel free to send a PR. But only if you have time. Really :)

Much appreciated

**Review by twm — APPROVED** [review]
Looks reasonable to me. Thanks Adi!

**Comment by adiroiban** [comment]
Thanks for the review.

**Comment by hynek** [comment]
sorry for coming late, but I've been secretly doing the rst → md transformation of the releases and it's really easy so it might be worth adding?

The command line is `pandoc --wrap=none --from rst --to gfm` with stdin/stdout. So to simply transform the current clipboard:

- on macOS it's `pbpaste | pandoc --wrap=none --from rst --to gfm | pbcopy`
- on Linux `xclip -selection clipboard -o | pandoc --wrap=none --from rst --to gfm | xclip -selection clipboard` or `xsel --clipboard --output | pandoc --wrap=none --from rst --to gfm | xsel --clipboard --input`
- on Windows `Get-Clipboard | pandoc --wrap=none --from rst --to gfm | Set-Clipboard`

(Linux & Windows untested)

**Comment by adiroiban** [comment]
I will keep this in mind for the next release, and we can update the docs.

----------

Rather than doing pandoc, maybe it is worth also having a NEWS.md file

This can help as a showcase for MD support in towncrier.

I guess that in these days, MD is more popular than RST so we should consider .MD as first class format in `towncrier`

**Comment by hynek** [comment]
That's a great idea – there seems still to be the impression that Towncrier is rst-only.

**Pull request merged**
