### PR TITLE
Stop writing title twice when title_format is specified

### LINKED ISSUE #346: title repeated twice when title_format is set
First of all, I would like to thank everyone working on this project. It eases our changelog generation a lot!

After upgrading our dependencies I have spotted some changed behavior. To illustrate this, I have created a fresh Python 3.9.4 project with just minimal code and `towncrier==21.3.0`.

When I configure `towncrier` like this:

```
[tool.towncrier]
title_format = "{version} ({project_date})"
```

Then the output of `towncrier build --version=0.1 --draft` is

```
0.1 (2021-04-27)
=================

Features
--------

- This is only a test. (#1)
```

as expected. However, the content of `NEWS.rst` after `towncrier build --version=0.1` is

```
0.1 (2021-04-27)0.1 (2021-04-27)
================

Features
--------

- This is only a test. (#1)
```

where we can see that the title is duplicated.

### LINKED ISSUE #352: Top line is applied twice
Hi,
with the latest version of towncrier the top line is twice applied leading to a weird text and invalid rST.

__pyproject.toml__
```toml
[tool.towncrier]
filename = "CHANGELOG.rst"
directory = "news/"
title_format = "{version} ({project_date})"

  [[tool.towncrier.type]]
  directory = "feature"
  name = "Features"
  showcontent = true
```

__news/123.feature__
```rst
dummy
```
__CHANGELOG.rst__
```rst
.. towncrier release notes start
```

If I now execute `towncrier --yes  --version 0.50.0`, teh following text is generated:

__CHANGELOG.rst__
```rst
0.50.0 (2021-06-28)0.50.0 (2021-06-28)
===================

Features
--------

- dummy (#1234)


.. towncrier release notes start
```

### PR DESCRIPTION
**Pull request by pquentin**
Closes #346

The title is already rendered in `content`. This does not fix draft mode, but that is recorded in a separate issue.

### CODE REVIEW

**Comment by pquentin** [comment]
To be clear, the coverage isn't actually decreasing, it's just that I removed a line that was tested.

**Comment by decaz** [comment]
@adiroiban @graingert @altendky @hukkin could you merge and release it, please?

**Comment by adiroiban** [comment]
Sorry for the delay. Let's merge this :)

Yes. coverage is expected to decrease when removing a file. I will fix it as part of the release branch.

**Review by adiroiban — APPROVED** [review]

**Comment by adiroiban** [comment]
I don't think that i will have time to do a release soon.
The release process is here and I think that anyone can create the release branch https://github.com/twisted/towncrier/blob/master/CONTRIBUTING.rst

I can review the release and if need i can create the tag for the release.

Thanks!

**Pull request merged**
