### PR TITLE
Fixup release instructions

### PR DESCRIPTION
**Pull request by altendky**
Just whatever I catch while doing the releases.

Draft for:
- [ ] Tagging on a branch isn't great when you then squash-merge it (which is the default)
- [ ] Tagging on the branch also results in a double build https://github.com/twisted/towncrier/pull/332#issuecomment-812777833
- [ ] The newsfragment creation and consumption to keep the build happy is silly.  Should note this until #309 (I think?) addresses this.

### CODE REVIEW

**Comment by adiroiban** [comment]
Any plan to continue working on this, or we can merge the current changes?

I did some minor changes to CONTRIBUTING.rst while doing the last release.

**Comment by altendky** [comment]
Go for it.  Maybe the checklist in the OP would make sense to add as notes in the instructions until they are addressed?

**Comment by adiroiban** [comment]
> The newsfragment creation and consumption to keep the build happy is silly.

I hope this will be fixed once #337 is merged.

----------

>  Tagging on a branch isn't great when you then squash-merge it (which is the default)

I am not sure what is the issue here.

You tag the code that is released.
It's only for reference.

--------

> Tagging on the branch also results in a double build

I am not sure what is the issue there.

When you create a tag, we run all the checks to make sure we don't release something for which the tests are broken.

This is the strict release process.
I am fine with it.

I would also be fine, that when a tag is created, to only run the release task and don't re-run the tests.

The idea is that for a PR you see the test green and then you manually create the tag/release.

**Comment by adiroiban** [comment]
> I find it a bit weird when a project's last release (or all of them for that matter) do not exist in the history of the main branch.

True. But but this is what you get when play god and rewrite the history :)

The changes were made into small commits, but with a squash you pretend that everything was a single big commit :)

I got used to that.

In practice, if a need to do a backport for an older release, I always create a new branch from tag and for me it's not really an issue.

So.. is this PR still a draft?

Can we merge it? Thanks!

**Review by adiroiban — APPROVED** [review]
Ready to land. Thanks!

**Pull request merged**
