### PR TITLE
Get rid of setup.cfg

### PR DESCRIPTION
**Pull request by hynek**
The only option present in setup.cfg has been available in setup.py for a fews years (if not always) already. :)

### CODE REVIEW

**Comment by hynek** [comment]
Yeah that coverage decrease ain't my fault. :D

**Review by adiroiban — APPROVED** [review]
It this makes people happy we can merge it.

And I think that this works for towncier.

---------

Just asking ?

What is wrong with having a setup.py

I am using the setup.py for `python setup.py bdist_wheel` and then publish in a private repo
... if you are paranoid and don't trust PyPi :)

**Comment by hynek** [comment]
> What is wrong with having a setup.py

This is removing setup.**cfg** that has only one line in it, not setup.py. :)

**Comment by hynek** [comment]
for the sake of completion: you can – [and should](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html) – build without invoking setup.py. The cleanest way is using https://pypa-build.readthedocs.io/

**Pull request merged**
