### PR TITLE
Release 23.10.0

### LINKED ISSUE #554: Release 23.10.0
Dedicated to  @iliakur  :)

### PR DESCRIPTION
**Pull request by adiroiban**
# Description

Fixes #554

Followed the instructions from https://github.com/twisted/towncrier/blob/trunk/RELEASE.rst

### CODE REVIEW

**Comment by adiroiban** [comment]
GitHub RC at https://github.com/twisted/towncrier/releases/tag/23.10.0rc1

GHA job for publish at https://github.com/twisted/towncrier/actions/runs/6615553105/job/17968058888

PyPi RC at https://pypi.org/project/towncrier/23.10.0rc1/

this is ready for review.

If all is ok, I will trigger the final release.

**Review by glyph — APPROVED** [review]
LGTM

**Comment by adiroiban** [comment]
Thanks for the review. 

Final release done.

GitHub Release  https://github.com/twisted/towncrier/releases/tag/23.10.0

GHA publish job  https://github.com/twisted/towncrier/actions/runs/6624926699/job/17994959205

PyPi https://pypi.org/project/towncrier/23.10.0/

**Comment by webknjaz** [comment]
@adiroiban do you have a release checklist somewhere? May I suggest adding GH Discussions there? It's only possible on GH Release creation, not when it's out already. I noticed that some of the recent releases have discussions attached to them. Personally, I tend to automate stuff so I include that setting in the release scripts..

**Comment by webknjaz** [comment]
@adiroiban by the way, my PyPUG guide got updated recently and it includes an example of signing the artifacts with sigstore (together with secretless publishing) if that's something you'd be open to integrating.. https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by adiroiban** [comment]
I only have:

>  Followed the instructions from https://github.com/twisted/towncrier/blob/trunk/RELEASE.rst

Do people need to discuss a `towncrier` release?

I can click that option next time, no problem :)

I will not have time to setup signing publishing anytime.

**Comment by webknjaz** [comment]
I think a discussion attached to a release of any project is an obvious place for feedback related to that specific release..

As for signing, I can look into it sometime, if there's any interest.

**Pull request merged**
