### PR TITLE
#659 Release 24.8.0

### LINKED ISSUE #659: Release 24.8.0
Just to track the new release

### PR DESCRIPTION
**Pull request by adiroiban**
# Description

Fixes #659

Follow the release process from here https://towncrier.readthedocs.io/en/latest/release.html

### CODE REVIEW

**Comment by adiroiban** [comment]
RC1 triggered here https://github.com/twisted/towncrier/actions/runs/10444975505

pypi package at https://pypi.org/project/towncrier/24.8.0rc1/

please check the review candidate and report any issues or if this is ready for the final relase.

thanks

**Comment by freakboy3742** [comment]
@adiroiban 24.8.0rc1 seems to [work as expected in my testing](https://github.com/beeware/toga-chart/actions/runs/10482258878/job/29033083870).

**Comment by glyph** [comment]
Thanks @freakboy3742 !

**Comment by adiroiban** [comment]
Thanks for the review.
The final release was triggered here https://github.com/twisted/towncrier/actions/runs/10527743725

**Pull request merged**
