### PR TITLE
Replace codecov with something simpler for now to fix CI

### PR DESCRIPTION
**Pull request by hynek**
The codecov package has been yanked from PyPI: https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259

If someone wants to figure out their new uploader, be my guest of course.

### CODE REVIEW

**Comment by hynek** [comment]
Please note that the codecov/patch check can't pass, but I didn't got forward to remove it before this is agreed on.

**Comment by adiroiban** [comment]
There is this PR that was not reverted, since it doesn't work with non-contributors. - https://github.com/twisted/towncrier/pull/447

---------

From what I know, codecov wants you to use the ["universal" uploader](https://github.com/codecov/uploader) or their dedicated GHA action (which uses bash)


If is the ["standard" Python example](https://github.com/codecov/python-standard/blob/master/.github/workflows/python-standard.yml) from codecov

**Comment by adiroiban** [comment]
I think that we can also keep only the current task and stop using codecov.

I like codecov and I use it for work, but at the same time, the current job is good enough, and we don't have to depend on external software.

**Comment by hynek** [comment]
> I think that we can also keep only the current task and stop using codecov.
> 
> I like codecov and I use it for work, but at the same time, the current job is good enough, and we don't have to depend on external software.

Can we merge then?

**Review by adiroiban — APPROVED** [review]
Let's merge.

It would have been nice to have the command from ci.yaml defined inside nox ... but this should not be a blocker.

I try to have as little as possible inside the GHA YAML file.

It makes it easier for dev to troubleshoot, reuse, re-run a command on their local dev env.

---------

I have disabled codecov branch protection from here https://github.com/twisted/towncrier/settings/branch_protection_rules/1000593

**Comment by hynek** [comment]
Thanks Adi!

**Pull request merged**
