### PR TITLE
Move man page to section 7

### LINKED ISSUE #469: Move master-document manual page to "overview" manual section
The Sphinx configuration currently builds a single manual page, from the entire master document. In `conf.py`:

```python
man_pages = [(master_doc, "towncrier", "Towncrier Documentation", [author], 1)]
```

The resulting manual page does not meet the conventions for section 1 of the manual ("User Commands"). (See the `man-pages(7)` manual page.)

The document should instead be in the manual section 7 ("Overview"), to describe the Towncrier system as a whole.

### PR DESCRIPTION
**Pull request by hynek**
fixes #469

### CODE REVIEW

**Review by exarkun — APPROVED** [review]

**Comment by adiroiban** [comment]
I don't know if this helps.

From what I can see, we don't build the man pages using Sphinx.

And in this PR, this looks like a Sphinx only change.

--------

I don't think that we have any official `man` page version of the doc.

The plan is to use the `click` man page generator helper to generate a man page version of the towncrier CLI tool ... so `click-man towncrier`

Some work here https://github.com/twisted/towncrier/pull/395

--------

So maybe is best to remove the man page info from Sphinx, as that configuration is not used.

**Comment by hynek** [comment]
My presumption here was that distros use it. If we ever have a replacement, sure let's kill it then.

**Comment by bignose-debian** [comment]
> I don't think that we have any official `man` page version of the doc.

The existing documentation is suitable, now that it is moved to manual section 7 to describe the Towncrier system as a whole.

There still is not an official manual page for the 'towncrier' command, suitable for manual section 1. You're correct on that.

> The plan is to use the `click` man page generator helper to generate a man page version of the towncrier CLI tool ... so `click-man towncrier`

I look forward to that being part of the build system.

> So maybe is best to remove the man page info from Sphinx, as that configuration is not used.

I don't see a need to remove this? The two manual pages (one in section 7, one in section 1) serve different purposes, both are useful. See the 'man-pages(7)' manual page for more.

**Comment by adiroiban** [comment]
OK. Makes some sense.

But we don't put any effort into making sure that the Sphinx docs pages are readable as man pages.

I think that if distro want/need a man page, is best to either use click-man to generate the man pages or use a stub page that direct to the webpage.

We now have versioned documentation - https://towncrier.readthedocs.io/en/22.12.0/

So distros can link to older/pin towncrier versions.

**Comment by bignose-debian** [comment]
> But we don't put any effort into making sure that the Sphinx docs pages are readable as man pages.

That's understandable, though disappointing. The Unix manual system is an important part of keeping documentation available in the existing standard system directly on the host, even when offline.

> I think that if distro want/need a man page, is best to either use click-man to generate the man pages

I look forward to this being part of the build system for Towncrier.

> or use a stub page that direct to the webpage.

That would defeat the purpose, since the Unix manual is intended to be documentation directly on the same host. It should be document the topics covered even when offline.

**Pull request merged**
