### PR TITLE
Remove basepython = python3.6 for checks

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
I don't really know why #323 was only ok until it got merged...  Maybe the underlying Linux image changed and lost 3.6?  But, I don't really have a strong need to have these versions pinned locally nor to duplicate them from the GHA config where they are 3.8.

**Comment by adiroiban** [comment]
Looks good. Looking forward for the final review :)

**Comment by altendky** [comment]
Supposedly GHA is back online...

**Review by adiroiban — APPROVED** [review]
Thanks. Ready to merge!

**Pull request merged**
