### PR TITLE
Release 22.8.0

### LINKED ISSUE #404: Release 22.8.0
I think it is time to do a new release.

The important feature is the "check" that will be skip if the NEWS file is modified...as this is a sign of a release branch

### PR DESCRIPTION
**Pull request by adiroiban**
# Description

Fixes #404

This is the release branch for 22.8.0

Release candidated published - https://pypi.org/project/towncrier/22.8.0rc1/
Docs at https://towncrier--405.org.readthedocs.build/en/405/

### CODE REVIEW

**Comment by adiroiban** [comment]
I think that this is ready for review

needs-review

**Comment by adiroiban** [comment]
I did a close and open to trigger the Read the docs build.

**Review by exarkun — APPROVED** [review]
Looks good to me.

**Comment by adiroiban** [comment]
Many thanks for the fast review.

I have triggered the release process via GitHub UI - https://github.com/twisted/towncrier/releases/tag/22.8.0

Hope all is ok.

I will then update version to a post0 (or dev0 as I think there is no support for post) 

And merge this.

**Pull request merged**
